# LaTeX2HTML 95.1 (Fri Jan 20 1995)
# Associate image original text (scrambled) with physical files.

$key = q/{_inline}$^sY^Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img186.gif">'; 
$key = q/{_inline}$v^Omega_i,j${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img121.gif">'; 
$key = q/{_inline}$d_*${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img169.gif">'; 
$key = q/{displaymath}a^Omega-N_*stackrelmboxemQuadtreeInterpolatehrulefill_;SPM_gt;tildea^Omega-N+1{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img68.gif">'; 
$key = q/{_inline}$V^Omega-N+1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img106.gif">'; 
$key = q/{_inline}$P[I_k=L_lmidcalC(Y);calK]${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img201.gif">'; 
$key = q/{_inline}$V^Omega-N${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img62.gif">'; 
$key = q/{_inline}$P[I_k=L_mmidcalC(Y);calK]${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img202.gif">'; 
$key = q/{_inline}$L_0${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img199.gif">'; 
$key = q/{_inline}$C${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img19.gif">'; 
$key = q/{displaymath}arrayrclU(a^Omega-1);SPM_amp;stackrelDelta=;SPM_amp;ln(P_X^Omega-1)P_gibbs[X^Omega-1=a^Omega-1];SPM_amp;stackrelDelta=;SPM_amp;exp(U(a^Omega-1)).array{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img155.gif">'; 
$key = q/{_inline}$mu^Om${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img127.gif">'; 
$key = q/{_inline}$tildea^Omega-N+1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img70.gif">'; 
$key = q/{displaymath}a_i_*=argmax_a_iP[X_i=a_i|C_i;K_i,X_j=a_j,jnei]{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img49.gif">'; 
$key = q/{_inline}$calY=X+W${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img114.gif">'; 
$key = q/{_inline}$L_l${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img196.gif">'; 
$key = q/{_inline}$z(i,j),foralli,j${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img168.gif">'; 
$key = q/{_inline}$calC(Y)=Y${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img12.gif">'; 
$key = q/{displaymath}z=fracbfd{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img173.gif">'; 
$key = q/{_inline}$K^Omega-N+1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img105.gif">'; 
$key = q/{_inline}$l=0,1,cdotsM${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img197.gif">'; 
$key = q/{_inline}$X^Om${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img132.gif">'; 
$key = q/{displaymath}a^Omega-n_*stackrelmboxQuadtreeInterpolatehrulefill_;SPM_gt;tildea^Omega-n+1{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img83.gif">'; 
$key = q/{_inline}$P[X^Omega=a^Om|C^Omega;K^Omega]${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img91.gif">'; 
$key = q/{_inline}$n=N,cdots,0${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img93.gif">'; 
$key = q/{figure}centerlinepsfigfigure=..COLORFIGunsup_scheme.ps,width=0.9textwidthlabelfig:unsup_scheme{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img164.gif">'; 
$key = q/{_inline}$hatU${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img160.gif">'; 
$key = q/{_inline}${x^L(i,j)}${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img170.gif">'; 
$key = q/{table}centertabular||l|l|l|l|l||hlinehlineVisiontask;SPM_amp;Modules;SPM_amp;Corevarib;SPM_amp;Knowledge;SPM_amp;Attribute_inline$V$_inline;SPM_amp;Integrated;SPM_amp;_inline$C$_inline;SPM_amp;_inline$K$_inline;SPM_amp;_inline$X$_inlinehlinehlinecolor;SPM_amp;(i)parameter;SPM_amp;degraded;SPM_amp;(i)degradationmodel;SPM_amp;restoredimage;SPM_amp;estimation,;SPM_amp;color;SPM_amp;_inline$calY=calA+W$_inline;SPM_amp;imagerestoration;SPM_amp;(ii)restoration;SPM_amp;image;SPM_amp;(ii)_inline$W$_inlineisGaussian;SPM_amp;hlinestereo;SPM_amp;(i)feature;SPM_amp;stereo;SPM_amp;(i)precomputededges;SPM_amp;disparityvision;SPM_amp;extraction;SPM_amp;image;SPM_amp;(ii)disparityrange;SPM_amp;ordepth;SPM_amp;(ii)matching;SPM_amp;pair;SPM_amp;(iii)disparityvaries;SPM_amp;map;SPM_amp;(iii)interpolation;SPM_amp;;SPM_amp;smoothly;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;(iv)epipolarconstraint;SPM_amp;hlineimage;SPM_amp;(i)segmentation;SPM_amp;greylevels,;SPM_amp;aprioriknowledge;SPM_amp;inter-interpretation;SPM_amp;(ii)image;SPM_amp;scenebased;SPM_amp;;SPM_amp;pretations;SPM_amp;interpretation;SPM_amp;features;SPM_amp;;SPM_amp;hlinehlinetabularcenterlabeltab:probs{table}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img113.gif">'; 
$key = q/{displaymath}a^Omega-N+1_*=argmax_a^Omega-N+1P[X^Omega-N+1=a^Omega-N+1|C^Omega-N+1;K^Omega-N+1]{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img75.gif">'; 
$key = q/{_inline}${z}${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img174.gif">'; 
$key = q/{_inline}${calC(Y);calK}${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img16.gif">'; 
$key = q/{_inline}$cdots${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img61.gif">'; 
$key = q/{displaymath}v^Omega_i,j=left{arraycl1;SPM_amp;mboxif;;;;f_v(a_i,j^Omega,a_i,j-1^Omega);SPM_gt;thresh0;SPM_amp;mboxotherwisearrayright.{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img123.gif">'; 
$key = q/{_inline}$Nne0${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img63.gif">'; 
$key = q/{_inline}$i=1,cdots,m${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img48.gif">'; 
$key = q/{_inline}$Omega-N+1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img177.gif">'; 
$key = q/{displaymath}a^Omega-n_*=argmax_a^Omega-nP[X^Omega-n=a^Omega-n|C^Omega-n;K^Omega-n]{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img82.gif">'; 
$key = q/{displaymath}a^Omega-N_*=argmax_a^Omega-NP[X^Omega-N=a^Omega-N|C^Omega-N;K^Omega-N]{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img65.gif">'; 
$key = q/{_inline}$L${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img194.gif">'; 
$key = q/{_inline}$I_k${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img195.gif">'; 
$key = q/{displaymath}a_*=argmax_aP[calA=a|calC(Y);calK].{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img26.gif">'; 
$key = q/{_inline}$^sY^Om${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img188.gif">'; 
$key = q/{_inline}$I_*${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img190.gif">'; 
$key = q/{_inline}$V^Om${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img57.gif">'; 
$key = q/{_inline}$7frac12${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img179.gif">'; 
$key = q/{_inline}$V${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img54.gif">'; 
$key = q/{_inline}$P_calA${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img152.gif">'; 
$key = q/{_inline}$calA=a_*${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img25.gif">'; 
$key = q/{displaymath}I_*=argmax_bfcalIin{calL}^nP[bfcalI|calC(Y);calK]{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img191.gif">'; 
$key = q/{displaymath}d^Omega-N+1_2stari+k,2starj+l=2stard^Omega-N_i,j,0lei,jle2^Omega-N-1mboxand0lek,lle1.{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img178.gif">'; 
$key = q/{_inline}$Omega-N${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img176.gif">'; 
$key = q/{_inline}$C^Om${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img89.gif">'; 
$key = q/{_inline}$a^Omega-N_k*${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img100.gif">'; 
$key = q/{displaymath}a^Omega-N_i*=argmax_a^Omega-N_iP[X^Omega-N_i=a^Omega-N_i|C^Omega-N_i;K^Omega-N_i,X^Omega-N_j=a^Omega-N_j,jnei]{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img95.gif">'; 
$key = q/{_inline}${x^R(i,j)}${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img166.gif">'; 
$key = q/{_inline}$a^Omega-N+1_*${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img74.gif">'; 
$key = q/{displaymath}a^Omega-N_k*stackrelmboxemQuadtreeInterpolatehrulefill_;SPM_gt;tildea_k^Omega-N+1{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img102.gif">'; 
$key = q/{_inline}$Y${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img9.gif">'; 
$key = q/{_inline}$i=0,1,cdotsm${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img51.gif">'; 
$key = q/{_inline}$U(a^Omega-1)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img157.gif">'; 
$key = q/{_inline}$calY=calHX+W${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img163.gif">'; 
$key = q/{displaymath}a^Omega-N+1_i*=argmax_a^Omega-N+1_iP[X^Omega-N+1=a^Omega-N+1_i|C^Omega-N+1;K^Omega-N+1].{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img109.gif">'; 
$key = q/{displaymath}h^Omega_i,j=left{arraycl1;SPM_amp;mboxif;;;;f_h(a_i,j^Omega,a_i-1,j^Omega);SPM_gt;thresh0;SPM_amp;mboxotherwisearrayright.{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img124.gif">'; 
$key = q/{figure}centerlinepsfigfigure=..STEREOFIGnew_integ.ps,width=0.9textwidthlabelfig:stereo{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img180.gif">'; 
$key = q/{_inline}$tildea^Omega-n+1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img84.gif">'; 
$key = q/{_inline}$V^Omega-1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img59.gif">'; 
$key = q/{_inline}$V^Omega-2${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img60.gif">'; 
$key = q/{_inline}$K^Om${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img90.gif">'; 
$key = q/{_inline}$|a^Omega_i,j|^2=(^1a^Omega_i,j)^2+(^2a^Omega_i,j)^2+(^3a^Omega_i,j)^2${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img119.gif">'; 
$key = q/{_inline}$P[calA=a|calC(Y);calK]${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img24.gif">'; 
$key = q/{displaymath}d_*=argmin_dsum_i,jleft[x^L(i,j)-x^R(i,j+d(i,j))right]^2{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img172.gif">'; 
$key = q/{_inline}$i=1,cdotsm${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img41.gif">'; 
$key = q/{_inline}$a^Omega-N_i*${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img96.gif">'; 
$key = q/{_inline}$sigma^Om${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img129.gif">'; 
$key = q/{_inline}$K${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img111.gif">'; 
$key = q/{_inline}$K^Omega-n+1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img85.gif">'; 
$key = q/{_inline}$X^Omega=a^Om_*${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img92.gif">'; 
$key = q/{_inline}$a^Omega-N_*${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img64.gif">'; 
$key = q/{_inline}$2^Omegatimes2^Om${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img183.gif">'; 
$key = q/{_inline}$Om${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img58.gif">'; 
$key = q/{_inline}$a^Omega-N+1_i*${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img108.gif">'; 
$key = q/{_inline}$a_i_*${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img50.gif">'; 
$key = q/{_inline}$V_3${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img39.gif">'; 
$key = q/{figure}centerlinepsfigfigure=int_mult.ps,width=0.9textwidthlabelfig:int_mult{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img27.gif">'; 
$key = q/{_inline}$V_2${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img38.gif">'; 
$key = q/{_inline}$V_1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img29.gif">'; 
$key = q/{_inline}$X${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img4.gif">'; 
$key = q/{_inline}$hatU(a^Omega-1)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img158.gif">'; 
$key = q/{_inline}$V_m${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img33.gif">'; 
$key = q/{_inline}$^ka^Omega_i,j${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img120.gif">'; 
$key = q/{_inline}$Omega-1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img145.gif">'; 
$key = q/{_inline}$gamma^Om${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img131.gif">'; 
$key = q/{_inline}$h^Omega_i,j${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img122.gif">'; 
$key = q/{_inline}$V_j${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img35.gif">'; 
$key = q/{_inline}$V_i${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img34.gif">'; 
$key = q/{figure}centerlinepsfigfigure=..IMAGESint_block.ps,width=5inlabelfig:inter_scheme{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img204.gif">'; 
$key = q/{_inline}$Y^Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img181.gif">'; 
$key = q/{_inline}$P_X^Omega-1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img154.gif">'; 
$key = q/{figure}centertabularcImage_inline$downarrow$_inline_inline$swarrow$_inlinefboxFeatureExtraction_inline$searrow$_inlinetabulartabularcccc_inline$bullet$_inlinemorefeatures_inline$_searrow$_inline;SPM_amp;hspace0.2cm;SPM_amp;hspace0.2cm;SPM_amp;_inline$_swarrowbullet$_inlinelessfeaturestabulartabularc_inline$swarrow$_inlinefboxFeatureMatching_inline$searrow$_inlinetabulartabularcccl_inline$bullet$_inlinefalsematches;SPM_amp;hspace0.2cm;SPM_amp;hspace0.2cm;SPM_amp;_inline$bullet$_inlinebfcorrectmatches_inline$bullet$_inlinecomputationally;SPM_amp;;SPM_amp;;SPM_amp;_inline$bullet$_inlinebfcomputationallymorecomplex;SPM_amp;;SPM_amp;;SPM_amp;bflesscomplex_inline$downarrow$_inline;SPM_amp;;SPM_amp;;SPM_amp;_inline$downarrow$_inline[0.5cm]_inline$bullet$_inlinebfdensedepthmap_inline$_searrow$_inline;SPM_amp;;SPM_amp;;SPM_amp;_inline$_swarrowbullet$_inlinesparsedepthmap(falsedepthpoints);SPM_amp;;SPM_amp;;SPM_amp;tabulartabularc_inline$swarrow$_inlinefboxDisparityInterpolation_inline$searrow$_inlinetabulartabularcccl_inline$bullet$_inlinepoorreconstruction;SPM_amp;hspace0.2cm;SPM_amp;hspace0.2cm;SPM_amp;_inline$bullet$_inlinepoorreconstructiontabularcenterlabelSTEREO_PROBLEM{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img175.gif">'; 
$key = q/{_inline}$X^Omega-1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img140.gif">'; 

1;

