# LaTeX2HTML 95.1 (Fri Jan 20 1995)
# Associate image original text (scrambled) with physical files.

$key = q/{_inline}$v^L,Omega,h^L,Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img187.gif">'; 
$key = q/{_inline}$x_i,j^R,Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img128.gif">'; 
$key = q/{_inline}$w(2)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img144.gif">'; 
$key = q/{_inline}$lambda_7^Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img79.gif">'; 
$key = q/{_inline}$U^Omega_interpol${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img121.gif">'; 
$key = q/{_inline}$v_i,j^R,Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img28.gif">'; 
$key = q/{_inline}$w(1)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img143.gif">'; 
$key = q/{_inline}$0leqm,nleq(P-1)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img11.gif">'; 
$key = q/{_inline}$barv^L,Omega,barh^L,Omega,barv^R,Omega,barh^R,Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img208.gif">'; 
$key = q/{_inline}$(i,j-1)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img45.gif">'; 
$key = q/{figure}[h]centerlinepsfigfigure=precomputed.ps,width=0.7textwidth{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img214.gif">'; 
$key = q/{_inline}$0leqm,nleq(2^Omega-1)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img18.gif">'; 
$key = q/{_inline}$calO^int_only(I2^2Omega)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img220.gif">'; 
$key = q/{_inline}$barh^Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img228.gif">'; 
$key = q/{_inline}$U^Omega_match${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img201.gif">'; 
$key = q/{_inline}$h_i,j^L,Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img70.gif">'; 
$key = q/{_inline}$x^R,Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img199.gif">'; 
$key = q/{_inline}$(i+1,j+2)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img108.gif">'; 
$key = q/{_inline}$w(0)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img142.gif">'; 
$key = q/{_inline}$(i+1,j-2)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img113.gif">'; 
$key = q/{_inline}$U^R,Omega_edge${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img89.gif">'; 
$key = q/{_inline}$b=0.25${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img151.gif">'; 
$key = q/{_inline}$w(-1)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img141.gif">'; 
$key = q/{_inline}${Delta^Omega_i,j}${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img158.gif">'; 
$key = q/{_inline}$v_i,j=1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img94.gif">'; 
$key = q/{_inline}$(0,2^Omega-1)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img135.gif">'; 
$key = q/{_inline}$lambda_1^Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img66.gif">'; 
$key = q/{_inline}$a=0.4${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img150.gif">'; 
$key = q/{_inline}$h^R,Omega_i,j+d^Omega_i,j${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img72.gif">'; 
$key = q/{_inline}$h^d,Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img204.gif">'; 
$key = q/{_inline}$Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img20.gif">'; 
$key = q/{_inline}$lambda_6^Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img78.gif">'; 
$key = q/{figure}centerlinepsfigfigure=x_fig.ps,width=0.5textwidth{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img159.gif">'; 
$key = q/{_inline}$(i,j)^th${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img132.gif">'; 
$key = q/{_inline}$0le(i,j)le2^Omega-1-1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img218.gif">'; 
$key = q/{_inline}$h_i,j^d,Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img51.gif">'; 
$key = q/{_inline}$d^Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img198.gif">'; 
$key = q/{_inline}$W^Omega_i,j${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img104.gif">'; 
$key = q/{_inline}$v^L,Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img171.gif">'; 
$key = q/{_inline}$d^Omega_i,j${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img95.gif">'; 
$key = q/{_inline}$Omega=8${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img224.gif">'; 
$key = q/{_inline}$oplus${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img54.gif">'; 
$key = q/{_inline}$sum_i=-2^i=2w(i)=1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img145.gif">'; 
$key = q/{_inline}$5times5${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img148.gif">'; 
$key = q/{_inline}$U_interpol^Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img205.gif">'; 
$key = q/{_inline}$barv^Omega_i,j${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img168.gif">'; 
$key = q/{_inline}$h_i,j^R,Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img34.gif">'; 
$key = q/{_inline}$f(x,y)stackrelDelta=x(1-y)+y(1-x)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img68.gif">'; 
$key = q/{_inline}$lambda_5^Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img77.gif">'; 
$key = q/{_inline}$(i+1,j-3)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img112.gif">'; 
$key = q/{_inline}$PtimesP${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img8.gif">'; 
$key = q/{figure}centerlinefboxpsfigfigure=diff.256.x,width=0.40textwidthfboxpsfigfigure=diff.256.x,width=0.20textwidthfboxpsfigfigure=diff.256.x,width=0.10textwidthfboxpsfigfigure=diff.256.x,width=0.05textwidthfboxpsfigfigure=diff.256.x,width=0.025textwidth{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img161.gif">'; 
$key = q/{_inline}$x_i,j^R,Omega-1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img131.gif">'; 
$key = q/{_inline}$h^Omega_i,j,h^R,Omega_i,j+d^Omega_i,j${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img73.gif">'; 
$key = q/{_inline}$barh_i,j^L,Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img37.gif">'; 
$key = q/{_inline}$(i-1,j)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img42.gif">'; 
$key = q/{_inline}$omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img222.gif">'; 
$key = q/{figure}centerlinepsfigfigure=new_integ.ps,width=0.7textwidth{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img3.gif">'; 
$key = q/{_inline}$h^R,Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img81.gif">'; 
$key = q/{_inline}$barh_i,j^R,Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img40.gif">'; 
$key = q/{_inline}$U^L,Omega_edge${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img90.gif">'; 
$key = q/{figure}centerlinefboxpsfigfigure=lattice.ps,width=0.40textwidth{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img105.gif">'; 
$key = q/{table}[h]centertabular|c|c|hlineModel;SPM_amp;Timetaken(inseconds)hlineMonoresolution;SPM_amp;cline1-1NoIntegration;SPM_amp;7700Precomputededge;SPM_amp;8400Interactiveedge;SPM_amp;9800Precomputedand;SPM_amp;Interactiveedges;SPM_amp;10000hlineMultiresolution;SPM_amp;cline1-1Precomputededge;SPM_amp;1000Interactiveedge;SPM_amp;1190hlinetabularcenter{table}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img239.gif">'; 
$key = q/{_inline}$v^Omega_i,j,v^R,Omega_i,j+d^Omega_i,j${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img74.gif">'; 
$key = q/{_inline}$(i,j+d^Omega_i,j)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img71.gif">'; 
$key = q/{_inline}$x^L,Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img185.gif">'; 
$key = q/{_inline}$d^Omega_i,j,d^Omega_i,k${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img118.gif">'; 
$key = q/{_inline}$(Omega-1)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img139.gif">'; 
$key = q/{_inline}$U_edge^L,Omega,U_edge^R,Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img217.gif">'; 
$key = q/{_inline}$x_i,j^L,(Omega-1)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img137.gif">'; 
$key = q/{_inline}$w(-2)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img140.gif">'; 
$key = q/{_inline}$w(0)=a,w(1)=b,w(2)=c${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img147.gif">'; 
$key = q/{_inline}$longrightarrow${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img211.gif">'; 
$key = q/{_inline}$h_i,j+d_i,j^Omega^R,Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img83.gif">'; 
$key = q/{_inline}$(i,j)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img38.gif">'; 
$key = q/{_inline}$z_m,n${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img4.gif">'; 
$key = q/{_inline}$(1-h^L,Omega_i,j)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img62.gif">'; 
$key = q/{tabular}cc|c|c|c|c|c|cline3-7;SPM_amp;;SPM_amp;_inline$c^2$_inline;SPM_amp;_inline$bc$_inline;SPM_amp;_inline$ac$_inline;SPM_amp;_inline$bc$_inline;SPM_amp;_inline$c^2$_inlinecline3-7;SPM_amp;;SPM_amp;_inline$bc$_inline;SPM_amp;_inline$b^2$_inline;SPM_amp;_inline$ab$_inline;SPM_amp;_inline$b^2$_inline;SPM_amp;_inline$bc$_inlinecline3-7calK;SPM_amp;=;SPM_amp;_inline$ac$_inline;SPM_amp;_inline$ab$_inline;SPM_amp;_inline$a^2$_inline;SPM_amp;_inline$ab$_inline;SPM_amp;_inline$ac$_inlinecline3-7;SPM_amp;;SPM_amp;_inline$bc$_inline;SPM_amp;_inline$b^2$_inline;SPM_amp;_inline$ab$_inline;SPM_amp;_inline$b^2$_inline;SPM_amp;_inline$bc$_inlinecline3-7;SPM_amp;;SPM_amp;_inline$c^2$_inline;SPM_amp;_inline$bc$_inline;SPM_amp;_inline$ac$_inline;SPM_amp;_inline$bc$_inline;SPM_amp;_inline$c^2$_inlinecline3-7{tabular}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img149.gif">'; 
$key = q/{_inline}$lambda_4^Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img76.gif">'; 
$key = q/{_inline}$beta_1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img235.gif">'; 
$key = q/{_inline}$calO^int+multicalO^int_onlyapprox17.5${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img226.gif">'; 
$key = q/{_inline}$v^d,Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img196.gif">'; 
$key = q/{_inline}$d_i,j^Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img49.gif">'; 
$key = q/{_inline}$v^R,Omega,h^R,Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img195.gif">'; 
$key = q/{_inline}$(i+2,j+2)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img109.gif">'; 
$key = q/{_inline}$z_i,j${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img5.gif">'; 
$key = q/{_inline}$U_edge^R,Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img123.gif">'; 
$key = q/{_inline}$x_m,n^L,Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img13.gif">'; 
$key = q/{_inline}$k^th${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img117.gif">'; 
$key = q/{_inline}$7times5${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img106.gif">'; 
$key = q/{_inline}$lambda_1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img234.gif">'; 
$key = q/{_inline}$gamma_1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img237.gif">'; 
$key = q/{_inline}$x_i,j^L,Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img136.gif">'; 
$key = q/{_inline}$P=2^Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img9.gif">'; 
$key = q/{_inline}$j^th${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img116.gif">'; 
$key = q/{_inline}$v_i,j^L,Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img64.gif">'; 
$key = q/{_inline}$mideta_i,jmid${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img97.gif">'; 
$key = q/{figure}centertabularcImage_inline$downarrow$_inline_inline$swarrow$_inlinefboxFeatureextractor_inline$searrow$_inlinetabulartabularcccc_inline$bullet$_inlinemorefeatures_inline$_searrow$_inline;SPM_amp;hspace0.2cm;SPM_amp;hspace0.2cm;SPM_amp;_inline$_swarrowbullet$_inlinelessfeaturestabulartabularc_inline$swarrow$_inlinefboxMatching_inline$searrow$_inlinetabulartabularcccl_inline$bullet$_inlinefalsematches;SPM_amp;hspace0.2cm;SPM_amp;hspace0.2cm;SPM_amp;_inline$bullet$_inlinebfcorrectmatches_inline$bullet$_inlinecomputationally;SPM_amp;;SPM_amp;;SPM_amp;_inline$bullet$_inlinebfcomputationallymorecomplex;SPM_amp;;SPM_amp;;SPM_amp;bflesscomplex_inline$downarrow$_inline;SPM_amp;;SPM_amp;;SPM_amp;_inline$downarrow$_inline[0.5cm]_inline$bullet$_inlinebfdensedepthmap_inline$_searrow$_inline;SPM_amp;;SPM_amp;;SPM_amp;_inline$_swarrowbullet$_inlinesparsedepthmap(falsedepthpoints);SPM_amp;;SPM_amp;;SPM_amp;tabulartabularc_inline$swarrow$_inlinefboxInterpolation_inline$searrow$_inlinetabulartabularcccl_inline$bullet$_inlinepoorreconstruction;SPM_amp;hspace0.2cm;SPM_amp;hspace0.2cm;SPM_amp;_inline$bullet$_inlinepoorreconstructiontabularcenter%labelSTEREO_PROBLEM{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img1.gif">'; 
$key = q/{_inline}$lambda_1^Omega(x_i,j^L,Omega-x_i,j-1^L,Omega)^2;SPM_gt;lambda_2^Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img65.gif">'; 
$key = q/{_inline}$aoplusb=1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img55.gif">'; 
$key = q/{_inline}$lambda_3^Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img75.gif">'; 
$key = q/{_inline}$barh^Omega_i,j${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img169.gif">'; 
$key = q/{figure}[h]centerlinepsfigfigure=estimated.ps,width=0.7textwidth{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img216.gif">'; 
$key = q/{_inline}$U_edge^L,Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img186.gif">'; 
$key = q/{_inline}$Delta^Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img215.gif">'; 
$key = q/{_inline}$(1-v^L,Omega_i,j)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img61.gif">'; 
$key = q/{_inline}$w(i)=w(-i)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img146.gif">'; 
$key = q/{_inline}$calO^int+multi(i(2^2Omega+2^2(Omega-1)+2^2(Omega-2)+cdots+2^2(Omega-(Omega-omega))))${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img221.gif">'; 
$key = q/{_inline}$h_i,j=1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img93.gif">'; 
$key = q/{_inline}$d^Omega_p,q${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img98.gif">'; 
$key = q/{_inline}$^^!!!!!!!!!!downarrow2${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img156.gif">'; 
$key = q/{_inline}$^^!!!!!!!!!!uparrow2${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img157.gif">'; 
$key = q/{_inline}$inW^Omega_i,j${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img99.gif">'; 
$key = q/{_inline}$h^L,Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img179.gif">'; 
$key = q/{_inline}$(barh,barv)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img213.gif">'; 
$key = q/{_inline}$v^R,Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img180.gif">'; 
$key = q/{_inline}${d_m,n}${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img19.gif">'; 
$key = q/{figure}centerlinefboxpsfigfigure=pentl.256.x,width=0.40textwidthfboxpsfigfigure=pentl.256.x,width=0.20textwidthfboxpsfigfigure=pentl.256.x,width=0.10textwidthfboxpsfigfigure=pentl.256.x,width=0.05textwidthfboxpsfigfigure=pentl.256.x,width=0.025textwidth{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img160.gif">'; 
$key = q/{table}[h]centertabular|c|c|hlineImage;SPM_amp;DisparityRangehlineRandomdotstereogram;SPM_amp;10Autopart;SPM_amp;36Pentagon;SPM_amp;5hlinetabularcenter{table}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img233.gif">'; 
$key = q/{_inline}$barv^Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img229.gif">'; 
$key = q/{_inline}$(x_i,j^L,Omega-x_i,j-1^L,Omega)^2${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img63.gif">'; 
$key = q/{_inline}$barv_i,j^L,Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img43.gif">'; 
$key = q/{_inline}$j+d^Omega_ijnek+d^Omega_ik${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img119.gif">'; 
$key = q/{_inline}$barv_i,j^R,Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img46.gif">'; 
$key = q/{_inline}$eta_i,j${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img96.gif">'; 
$key = q/{_inline}$v_i,j^d,Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img52.gif">'; 
$key = q/{_inline}$x_m,n^R,Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img17.gif">'; 
$key = q/{_inline}$Omega-1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img57.gif">'; 
$key = q/{_inline}$c=0.05${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img152.gif">'; 
$key = q/{}fboxcalK{}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img155.gif">'; 
$key = q/{_inline}$Delta^Omega_i,j${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img166.gif">'; 
$key = q/{_inline}$omega=3${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img225.gif">'; 
$key = q/{_inline}$Delta_i,j${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img212.gif">'; 
$key = q/{_inline}$calO^int+multi(i2^2Omega(1-(14)^(Omega-omega+1))(1-(14))${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img223.gif">'; 
$key = q/{_inline}$256time256${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img232.gif">'; 
$key = q/{_inline}$lambda_2^Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img67.gif">'; 
$key = q/{_inline}$v_i,j+d_i,j^Omega^R,Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img84.gif">'; 

1;

