# LaTeX2HTML 95.1 (Fri Jan 20 1995)
# Associate image original text (scrambled) with physical files.

$key = q/{_inline}${x^G_i,j+1,x^G_i,j-1,x^G_i-1,j,x^G_i+1,j}${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img189.gif">'; 
$key = q/{_inline}$17.218${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img171.gif">'; 
$key = q/{_inline}$Y^k=X^k+W^k${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img17.gif">'; 
$key = q/{_inline}$V_c${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img70.gif">'; 
$key = q/{_inline}$phi^k${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img71.gif">'; 
$key = q/{_inline}$3G(2^k)^2${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img112.gif">'; 
$key = q/{_inline}$x^R_i,j${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img185.gif">'; 
$key = q/{displaymath}v^k_i,j=left{arraycl1;SPM_amp;mboxif;;;;f_v(x_i,j^k,x_i,j-1^k);SPM_gt;thresh0;SPM_amp;mboxotherwisearrayright.{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img80.gif">'; 
$key = q/{_inline}$W${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img3.gif">'; 
$key = q/{_inline}$^1G^k${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img50.gif">'; 
$key = q/{_inline}$calA^k_i,j${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img26.gif">'; 
$key = q/{_inline}$left.right]${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img53.gif">'; 
$key = q/{_inline}$Y^k${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img16.gif">'; 
$key = q/{_inline}$calC:i,jinc${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img109.gif">'; 
$key = q/{_inline}$calW^k_i,j${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img32.gif">'; 
$key = q/{displaymath}|y^k-x^k|^2stackrelDelta=sum_q=1^3sum_i,j(^qy^k_i,j-^qx^k_i,j)^2,{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img85.gif">'; 
$key = q/{_inline}$U(x^k,phi^k)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img67.gif">'; 
$key = q/{_inline}$X^Omega-N=Y^Omega-N${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img128.gif">'; 
$key = q/{_inline}$;(Omega=8)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img153.gif">'; 
$key = q/{_inline}$I_3${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img14.gif">'; 
$key = q/{_inline}$U_p(a,h,v)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img179.gif">'; 
$key = q/{_inline}$I_2${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img13.gif">'; 
$key = q/{_inline}$I_1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img83.gif">'; 
$key = q/{_inline}$approx3${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img177.gif">'; 
$key = q/{_inline}$32times32${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img154.gif">'; 
$key = q/{_inline}$Y^Omega-1,Y^Omega-2,cdots,Y^Omega-N${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img126.gif">'; 
$key = q/{_inline}$(G^3)^(2^k)^2${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img101.gif">'; 
$key = q/{_inline}$(i,j)^th${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img184.gif">'; 
$key = q/{_inline}$Omega-N${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img127.gif">'; 
$key = q/{_inline}$15.027${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img170.gif">'; 
$key = q/{_inline}$calA^k${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img38.gif">'; 
$key = q/{displaymath}P[X^k=x^k]=frac1Z^kexp^-U(x^k,phi^k){displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img65.gif">'; 
$key = q/{_inline}$calG^Omega=left[right.${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img49.gif">'; 
$key = q/{_inline}$X^k${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img73.gif">'; 
$key = q/{_inline}$Omega=8${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img157.gif">'; 
$key = q/{_inline}$2^k${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img102.gif">'; 
$key = q/{_inline}$0.1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img180.gif">'; 
$key = q/{_inline}$0leqlambdaleq1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img119.gif">'; 
$key = q/{_inline}$X^Omega-kstackrelQuadtreeInterpolatehrulefill_;SPM_gt;tildecalA^Omega-k+1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img147.gif">'; 
$key = q/{_inline}$h^k_i,j${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img79.gif">'; 
$key = q/{_inline}$2^Omegatimes2^Om${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img123.gif">'; 
$key = q/{_inline}$^pW^k_i,j${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img54.gif">'; 
$key = q/{_inline}$^3G^k${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img52.gif">'; 
$key = q/{_inline}$^1calA^k${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img39.gif">'; 
$key = q/{_inline}$X${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img6.gif">'; 
$key = q/{_inline}$^2calA^k${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img40.gif">'; 
$key = q/{_inline}$Omega-k+3${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img132.gif">'; 
$key = q/{_inline}$^3calA^k${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img41.gif">'; 
$key = q/{displaymath}h^k_i,j=left{arraycl1;SPM_amp;mboxif;;;;f_h(x_i,j^k,x_i-1,j^k);SPM_gt;thresh0;SPM_amp;mboxotherwisearrayright.{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img81.gif">'; 
$key = q/{_inline}$]^T${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img42.gif">'; 
$key = q/{_inline}$256times256${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img182.gif">'; 
$key = q/{_inline}$hatcalA^Om${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img150.gif">'; 
$key = q/{_inline}$X^Omega-k${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img138.gif">'; 
$key = q/{_inline}$0lei,jle2^k-1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img33.gif">'; 
$key = q/{_inline}$G=256,2^k=256${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img113.gif">'; 
$key = q/{_inline}$calA${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img7.gif">'; 
$key = q/{_inline}$|cdot|${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img76.gif">'; 
$key = q/{_inline}$Y^Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img122.gif">'; 
$key = q/{_inline}$(k;SPM_gt;N)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img144.gif">'; 
$key = q/{_inline}$Omega-k${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img136.gif">'; 
$key = q/{_inline}$1leqp,qleq3${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img62.gif">'; 
$key = q/{_inline}$calW^k${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img36.gif">'; 
$key = q/{_inline}$cincalC${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img110.gif">'; 
$key = q/{_inline}$x^k_*${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img91.gif">'; 
$key = q/{_inline}$calY=X+W${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img15.gif">'; 
$key = q/{_inline}$^qG^k${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img47.gif">'; 
$key = q/{_inline}$x^k${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img72.gif">'; 
$key = q/{_inline}$approx15${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img129.gif">'; 
$key = q/{_inline}$calB${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img4.gif">'; 
$key = q/{_inline}$left[phi^Omega-k,(sigma^2)^Omega-kright]${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img140.gif">'; 
$key = q/{_inline}$(i,j)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img187.gif">'; 
$key = q/{_inline}$2^ktimes2^k${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img29.gif">'; 
$key = q/{_inline}$hatcalA^Omega-k=tildecalA^Omega-k${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img145.gif">'; 
$key = q/{_inline}$1leqpleq3${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img55.gif">'; 
$key = q/{_inline}$U_p(x^k,h^k,v^k)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img87.gif">'; 
$key = q/{_inline}$hatcalA${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img5.gif">'; 
$key = q/{_inline}$calY^k_i,j${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img30.gif">'; 
$key = q/{_inline}$k=Omega-3${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img155.gif">'; 
$key = q/{_inline}$calC${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img69.gif">'; 
$key = q/{_inline}$v^k_i,j${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img78.gif">'; 
$key = q/{_inline}$^qX_l,m^k${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img58.gif">'; 
$key = q/{figure}centerlinehfillpsfigfigure=COLORFIGscene_4_original.ps,width=1.5inhfillcenterlinehfill(a)hfillvspace2excenterlinehfillpsfigfigure=COLORFIGscene_4_noisy.ps,width=1.5inhfillpsfigfigure=COLORFIGscene_4_restored.ps,width=1.5inhfillcenterlinehfill(b)hfill(c)hfilllabelfig:scene_4{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img173.gif">'; 
$key = q/{table}centertabular||l||l|l|l|l||hlinehlineVisiontask;SPM_amp;Modules;SPM_amp;CoreVariables;SPM_amp;Knowledge;SPM_amp;Attribute_inline$V$_inline;SPM_amp;Integrated;SPM_amp;_inline$C$_inline;SPM_amp;_inline$K$_inline;SPM_amp;_inline$X$_inlinehlinehlinecolor;SPM_amp;(i)parameter;SPM_amp;degraded;SPM_amp;(i)degradationmodel;SPM_amp;restoredimage;SPM_amp;estimation;SPM_amp;color;SPM_amp;_inline$calY=calA+W$_inline;SPM_amp;imagerestoration;SPM_amp;(ii)restoration;SPM_amp;image;SPM_amp;(ii)_inline$W$_inlineisGaussian;SPM_amp;hlinehlinetabularcenterlabeltab:gen_cir{table}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img25.gif">'; 
$key = q/{figure}centerlinehfillpsfigfigure=COLORFIGscene_3_original.ps,width=1.5inhfillcenterlinehfill(a)hfillvspace2excenterlinehfillpsfigfigure=COLORFIGscene_3_noisy.ps,width=1.5inhfillpsfigfigure=COLORFIGscene_3_restored.ps,width=1.5inhfillcenterlinehfill(b)hfill(c)hfilllabelfig:scene_3{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img168.gif">'; 
$key = q/{_inline}${x^R_i,j+1,x^R_i,j-1,x^R_i-1,j,x^R_i+1,j}${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img188.gif">'; 
$key = q/{figure}centerlinehfillpsfigfigure=COLORFIGscene_2_original.ps,width=1.5inhfillcenterlinehfill(a)hfillvspace2excenterlinehfillpsfigfigure=COLORFIGscene_2_noisy.ps,width=1.5inhfillpsfigfigure=COLORFIGscene_2_restored.ps,width=1.5inhfillcenterlinehfill(b)hfill(c)hfilllabelfig:scene_2{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img162.gif">'; 
$key = q/{_inline}$^2G^k${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img51.gif">'; 
$key = q/{figure}centerlinehfillpsfigfigure=COLORFIGscene_1_original.ps,width=1.5inhfillcenterlinehfill(a)hfillvspace2excenterlinehfillpsfigfigure=COLORFIGscene_1_noisy.ps,width=1.5inhfillpsfigfigure=COLORFIGscene_1_restored.ps,width=1.5inhfillcenterlinehfill(b)hfill(c)hfilllabelfig:scene_1c{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img151.gif">'; 
$key = q/{_inline}$X^Omega-N${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img142.gif">'; 
$key = q/{_inline}$phi^k=left[mu^k,gamma^kright]^T${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img92.gif">'; 
$key = q/{_inline}$|x^k_i,j|^2=(^1x^k_i,j)^2+(^2x^k_i,j)^2+(^3x^k_i,j)^2.${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img77.gif">'; 
$key = q/{_inline}$Y${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img2.gif">'; 
$key = q/{figure}centerlinepsfigfigure=COLORrestore_model.ps,width=0.9textwidthlabelfig:restore_model{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img1.gif">'; 
$key = q/{_inline}$approx35${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img131.gif">'; 
$key = q/{_inline}$mu,gamma${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img160.gif">'; 
$key = q/{_inline}$P[cdot|cdot]${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img120.gif">'; 
$key = q/{_inline}$^pW_i,j^k${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img57.gif">'; 
$key = q/{displaymath}U(x^k,phi^k)=sum_cincalCV_c(x^k,phi^k),{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img68.gif">'; 
$key = q/{_inline}$G(2^k)^2${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img111.gif">'; 
$key = q/{_inline}$(sigma^2)^k${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img56.gif">'; 
$key = q/{figure}centerlinepsfigfigure=COLORFIGunsup_scheme.ps,width=0.95textwidthlabelfig:unsup_scheme{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img121.gif">'; 
$key = q/{_inline}$x^k,h^k,v^k${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img88.gif">'; 
$key = q/{_inline}$klongrightarrowk-1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img148.gif">'; 
$key = q/{_inline}$calY^k${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img34.gif">'; 
$key = q/{_inline}$phi^kstackrelDelta=left[mu^k,gamma^kright]^T${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img75.gif">'; 
$key = q/{_inline}$in[0,256]${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img48.gif">'; 
$key = q/{_inline}$15.129${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img163.gif">'; 
$key = q/{_inline}$Om${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img149.gif">'; 
$key = q/{_inline}$(l,m)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img60.gif">'; 
$key = q/{_inline}$2^Omega-Ntimes2^Omega-N${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img139.gif">'; 
$key = q/{_inline}$(256^3)^256^2-1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img114.gif">'; 
$key = q/{_inline}$approx${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img159.gif">'; 
$key = q/{_inline}$sigma${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img164.gif">'; 
$key = q/{_inline}$calY=calBX+W${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img8.gif">'; 
$key = q/{_inline}$eta_i,j${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img105.gif">'; 
$key = q/{_inline}$x^k_*,h^k_*,v^k_*${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img90.gif">'; 
$key = q/{_inline}$Z^kstackrelDelta=sum_x^kexp^-U(x^k,phi^k)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img66.gif">'; 
$key = q/{_inline}${x^B_i,j+1,x^B_i,j-1,x^B_i-1,j,x^B_i+1,j}${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img190.gif">'; 
$key = q/{_inline}$left[phi^Omega-N,(sigma^2)^Omega-Nright]${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img135.gif">'; 
$key = q/{_inline}$Y^Omega=X^Omega+W^Om${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img124.gif">'; 
$key = q/{_inline}$^qcalA_i,j^k${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img46.gif">'; 

1;

