# LaTeX2HTML 95.1 (Fri Jan 20 1995)
# Associate image original text (scrambled) with physical files.

$key = q/{_inline}$^1X^Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img26.gif">'; 
$key = q/{_inline}$(m,n)ineta_i,j${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img86.gif">'; 
$key = q/{_inline}$128times128${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img137.gif">'; 
$key = q/{_inline}$1leqp,qleq3${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img41.gif">'; 
$key = q/{table}centertabular|c|c|c|hline;SPM_amp;SNR(indB);SPM_amp;Iterations_inline$Omega$_inlinehlinehlineSupervisedMonoresolution(Figure3);SPM_amp;19.1855;SPM_amp;2000SupervisedMultiresolution(Figure4);SPM_amp;19.1250;SPM_amp;200UnsupervisedMultiresolution(Figure5);SPM_amp;19.0978;SPM_amp;200hlinetabularlabeltab:snrcenter{table}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img142.gif">'; 
$key = q/{_inline}$I_1,I_2,I_3${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img4.gif">'; 
$key = q/{_inline}$Omega=4${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img110.gif">'; 
$key = q/{_inline}$^2X^Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img27.gif">'; 
$key = q/{_inline}$hatX^Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img120.gif">'; 
$key = q/{_inline}$hatx^Omega(i,j)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img136.gif">'; 
$key = q/{_inline}$|x^Omega_i,j|^2=(^1x^Omega_i,j)^2+(^2x^Omega_i,j)^2+(^3x^Omega_i,j)^2${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img55.gif">'; 
$key = q/{_inline}$x^Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img70.gif">'; 
$key = q/{_inline}$^3X^Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img28.gif">'; 
$key = q/{_inline}$(i,j)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img88.gif">'; 
$key = q/{_inline}$2^Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img12.gif">'; 
$key = q/{_inline}$1leqpleq3${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img33.gif">'; 
$key = q/{_inline}$x^Omega_i,jincalG${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img91.gif">'; 
$key = q/{_inline}$left[U_p(x^Omega,h^Omega,v^Omega)right]${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img67.gif">'; 
$key = q/{_inline}$Omega=4,5,6${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img102.gif">'; 
$key = q/{table}centertabular|cc|c|c|c|hline;SPM_amp;(_inline$Omega$_inline);SPM_amp;_inline$sigma$_inline;SPM_amp;_inline$mu$_inline;SPM_amp;_inline$gamma$_inlinehlinehlineFigure3;SPM_amp;(7);SPM_amp;26.55;SPM_amp;0.00175;SPM_amp;16.29hlineFigure4;SPM_amp;(7);SPM_amp;24.80;SPM_amp;0.00359;SPM_amp;18.26;SPM_amp;(6);SPM_amp;8.34;SPM_amp;0.00476;SPM_amp;14.70;SPM_amp;(5);SPM_amp;5.33;SPM_amp;0.00285;SPM_amp;12.53;SPM_amp;(4);SPM_amp;4.208;SPM_amp;0.00449;SPM_amp;11.35hlineFigure5;SPM_amp;(6);SPM_amp;10.46;SPM_amp;0.00610;SPM_amp;14.32;SPM_amp;(5);SPM_amp;12.39;SPM_amp;0.00284;SPM_amp;6.23;SPM_amp;(4);SPM_amp;3.105;SPM_amp;0.00230;SPM_amp;20.19hlinetabularlabeltab:parametercenter{table}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img143.gif">'; 
$key = q/{_inline}$0lei,jle2^Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img16.gif">'; 
$key = q/{_inline}$I_3${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img7.gif">'; 
$key = q/{_inline}$I_2${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img6.gif">'; 
$key = q/{_inline}$I_1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img5.gif">'; 
$key = q/{_inline}$(G^3)^N^2${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img81.gif">'; 
$key = q/{}psfigfigure=lenna_monoresolution,width=0.2textwidth{}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img147.gif">'; 
$key = q/{_inline}$mu${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img1.gif">'; 
$key = q/{_inline}$W^Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img19.gif">'; 
$key = q/{_inline}$h^Omega_i,j=1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img58.gif">'; 
$key = q/{_inline}$U(x^Omega,phi^Omega)=sum_cinCV_c(x^Omega,phi^Omega)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img44.gif">'; 
$key = q/{_inline}$P(X^Omega=x^Omega)=frac1Ze^-U(x^Omega,phi^Omega)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img43.gif">'; 
$key = q/{_inline}$gamma${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img2.gif">'; 
$key = q/{_inline}$^qG^Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img30.gif">'; 
$key = q/{_inline}$Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img11.gif">'; 
$key = q/{_inline}$|y^Omega-x^Omega|^2=sum_q=1^3sum_i,j${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img64.gif">'; 
$key = q/{_inline}$GN^2${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img84.gif">'; 
$key = q/{}psfigfigure=lenna_noisy,width=0.2textwidth{}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img146.gif">'; 
$key = q/{}psfigfigure=lenna_multi_unsup,width=0.2textwidth{}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img149.gif">'; 
$key = q/{_inline}$13.73${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img139.gif">'; 
$key = q/{_inline}$f_v(x_i,j^Omega,x_i,j-1^Omega);SPM_gt;thresh${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img57.gif">'; 
$key = q/{_inline}$[^1x^Omega_i,j,^2x^Omega_i,j,^3x^Omega_i,j]in${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img92.gif">'; 
$key = q/{_inline}$approx7frac12${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img144.gif">'; 
$key = q/{_inline}$(k,l)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img39.gif">'; 
$key = q/{}psfigfigure=lenna_original,width=0.2textwidth{}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img145.gif">'; 
$key = q/{_inline}$phi^Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img50.gif">'; 
$key = q/{_inline}$W^Omega_i,j${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img15.gif">'; 
$key = q/{_inline}$sigma^Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img35.gif">'; 
$key = q/{_inline}$3GN^2${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img83.gif">'; 
$key = q/{_inline}$f_v(x_i,j^Omega,x_i-1,j^Omega);SPM_gt;thresh${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img59.gif">'; 
$key = q/{_inline}$X^Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img20.gif">'; 
$key = q/{_inline}$sum_x^Omegae^-U(x^Omega,phi^Omega)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img53.gif">'; 
$key = q/{_inline}$X^Omega_i,j${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img13.gif">'; 
$key = q/{_inline}$x^Omega,h^Omega,v^Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img68.gif">'; 
$key = q/{_inline}$in[0,256]${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img31.gif">'; 
$key = q/{_inline}$0leqlambdaleq1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img99.gif">'; 
$key = q/{_inline}$^qX_i,j^Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img29.gif">'; 
$key = q/{_inline}$[mu^Omega,gamma^Omega]^T${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img66.gif">'; 
$key = q/{_inline}$Omega=5${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img126.gif">'; 
$key = q/{_inline}$v^Omega_i,j=1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img56.gif">'; 
$key = q/{_inline}$I_1=(R+G+B)3${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img61.gif">'; 
$key = q/{_inline}$Y^Omega_i,j${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img14.gif">'; 
$key = q/{_inline}$^pW_i,j^Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img36.gif">'; 
$key = q/{_inline}$X^Omega(=Y^Omega)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img113.gif">'; 
$key = q/{_inline}$2^Omegatimes2^Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img40.gif">'; 
$key = q/{_inline}$hatX^Omega,Y^Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img132.gif">'; 
$key = q/{_inline}$[^1G^Omega,^2G^Omega,^3G^Omega]${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img93.gif">'; 
$key = q/{_inline}$(sigma^Omega)^2${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img34.gif">'; 
$key = q/{_inline}$eta_i,j${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img87.gif">'; 
$key = q/{_inline}$Omega=4,5,6,7${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img141.gif">'; 
$key = q/{_inline}$]^T${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img25.gif">'; 
$key = q/{_inline}$x^Omega+1(i,j)=hatx^Omega(2*i,2*j)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img134.gif">'; 
$key = q/{_inline}$sigma^2${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img3.gif">'; 
$key = q/{}psfigfigure=lenna_multiresolution,width=0.2textwidth{}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img148.gif">'; 
$key = q/{_inline}$^qX_k,l^Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img37.gif">'; 
$key = q/{_inline}$^pW^Omega_i,j${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img32.gif">'; 
$key = q/{_inline}$(^qy^Omega_i,j-^qx^Omega_i,j)^2${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img65.gif">'; 
$key = q/{_inline}$V_c(cdot)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img48.gif">'; 
$key = q/{_inline}$Y^Omega${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img77.gif">'; 
$key = q/{_inline}$Omega=7${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img138.gif">'; 

1;

